-- MySQL Script generated by MySQL Workbench
-- Fri May 15 18:43:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vitalis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vitalis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vitalis` DEFAULT CHARACTER SET utf8 ;
USE `vitalis` ;

-- -----------------------------------------------------
-- Table `vitalis`.`ambulancias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalis`.`ambulancias` (
  `id_patente` INT NOT NULL,
  `modelo_ambulancia` VARCHAR(45) NULL,
  `anio_fabricacion` DATE NULL,
  PRIMARY KEY (`id_patente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalis`.`especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalis`.`especialidad` (
  `idespecialidad` INT NOT NULL,
  `nombre_especialidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idespecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalis`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalis`.`medicos` (
  `id_matricula` INT NOT NULL,
  `nombre_medico` VARCHAR(45) NULL,
  `apellido_medico` VARCHAR(45) NULL,
  `especialidad_idespecialidad` INT NOT NULL,
  PRIMARY KEY (`id_matricula`, `especialidad_idespecialidad`),
  INDEX `fk_medicos_especialidad_idx` (`especialidad_idespecialidad` ASC) VISIBLE,
  CONSTRAINT `fk_medicos_especialidad`
    FOREIGN KEY (`especialidad_idespecialidad`)
    REFERENCES `vitalis`.`especialidad` (`idespecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalis`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalis`.`plan` (
  `idplan` INT NOT NULL,
  `tipo_plan` VARCHAR(45) NULL,
  PRIMARY KEY (`idplan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalis`.`afiliados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalis`.`afiliados` (
  `id_afiliado` INT NOT NULL,
  `nombre_afiliado` VARCHAR(45) NULL,
  `apellido_afiliado` VARCHAR(45) NULL,
  `numero_telefono_afiliado` DECIMAL NULL,
  `domicilio_afiliado` VARCHAR(45) NULL,
  `estado_pago_plan` TINYINT NULL,
  `plan_idplan` INT NOT NULL,
  PRIMARY KEY (`id_afiliado`, `plan_idplan`),
  INDEX `fk_afiliados_plan1_idx` (`plan_idplan` ASC) VISIBLE,
  CONSTRAINT `fk_afiliados_plan1`
    FOREIGN KEY (`plan_idplan`)
    REFERENCES `vitalis`.`plan` (`idplan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalis`.`motivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalis`.`motivo` (
  `idmotivo` INT NOT NULL,
  `nombre_motivo` VARCHAR(45) NULL,
  PRIMARY KEY (`idmotivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalis`.`gravedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalis`.`gravedad` (
  `idgravedad` INT NOT NULL,
  `categoria_gravedad` INT NULL,
  PRIMARY KEY (`idgravedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vitalis`.`incidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vitalis`.`incidente` (
  `idincidente` INT NOT NULL,
  `ambulancias_id_patente` INT NOT NULL,
  `medicos_id_matricula` INT NOT NULL,
  `afiliados_id_afiliado` INT NOT NULL,
  `fecha_hora_incidente` DATETIME NULL,
  `motivo_idmotivo` INT NOT NULL,
  `gravedad_idgravedad` INT NOT NULL,
  PRIMARY KEY (`idincidente`, `ambulancias_id_patente`, `medicos_id_matricula`, `afiliados_id_afiliado`, `motivo_idmotivo`, `gravedad_idgravedad`),
  INDEX `fk_incidente_ambulancias1_idx` (`ambulancias_id_patente` ASC) VISIBLE,
  INDEX `fk_incidente_medicos1_idx` (`medicos_id_matricula` ASC) VISIBLE,
  INDEX `fk_incidente_afiliados1_idx` (`afiliados_id_afiliado` ASC) VISIBLE,
  INDEX `fk_incidente_motivo1_idx` (`motivo_idmotivo` ASC) VISIBLE,
  INDEX `fk_incidente_gravedad1_idx` (`gravedad_idgravedad` ASC) VISIBLE,
  CONSTRAINT `fk_incidente_ambulancias1`
    FOREIGN KEY (`ambulancias_id_patente`)
    REFERENCES `vitalis`.`ambulancias` (`id_patente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidente_medicos1`
    FOREIGN KEY (`medicos_id_matricula`)
    REFERENCES `vitalis`.`medicos` (`id_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidente_afiliados1`
    FOREIGN KEY (`afiliados_id_afiliado`)
    REFERENCES `vitalis`.`afiliados` (`id_afiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidente_motivo1`
    FOREIGN KEY (`motivo_idmotivo`)
    REFERENCES `vitalis`.`motivo` (`idmotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_incidente_gravedad1`
    FOREIGN KEY (`gravedad_idgravedad`)
    REFERENCES `vitalis`.`gravedad` (`idgravedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
